<?php

/**
 * Implements hook_install().
 */
function custom_feed_migration_install() {
    // Install module configuration.
    \Drupal::service('config.installer')->installDefaultConfig('module', 'custom_feed_migration');
  }
  
  /**
   * Implements hook_uninstall().
   */
  function custom_feed_migration_uninstall() {
    // Uninstall module configuration.
    \Drupal::configFactory()->getEditable('custom_feed_migration.settings')->delete();
  }
  
